### PR TITLE
feat: add topic config

### PR DESCRIPTION
**Pull request by rdshoep**
Add the `topic` config item, support two mode:

1. Read from `msg.topic` ( same as before )
2. Use the given options[`completion`, `image`, `edit`, `turbo`] (reduce a `change` NODE-RED node)

### CODE REVIEW

**Comment by rdshoep** [comment]
Hi, @HaroldPetersInskipp :

You have added an expected feature to support `gpt4` yesterday. And you reformatted the `chatgpt.js` file in this commit.

What's your opinion about this PR's idea? 
If you agree, I will close this PR and create a new one to keep the diff clean~

**Comment by HaroldPetersInskipp** [comment]
Sounds like a great addition to the node. This should keep it user friendly while also making it easier for an alternative default mode to be set. To be honest, it's something I've been meaning to do. In the future I may also support setting additional properties like `msg.temperature` as well. However, I'm concerned that it may over-complicate the node making it more difficult for beginners to learn. I do believe selecting the mode should be included at the minimum though.

If you could bring it in line with the current changes to the repo, I would be happy to include your suggestion.

**Comment by HaroldPetersInskipp** [comment]
I've updated the node to version 1.2.4 to include a similar approximation to what this feature request is about. Does this resolve the request or do you have any additional feedback or improvements?

**Comment by rdshoep** [comment]
> I've updated the node to version 1.2.4 to include a similar approximation to what this feature request is about. Does this resolve the request or do you have any additional feedback or improvements?

Yes, I agree with your considerations regarding usability.

Users who use Node-Red are usually proficient in computer operation and familiar with the basic operation and usage of Node-Red. Therefore, the nodes developed using Node-Red's general setup mode will not have much impact on users. We mainly hope to reduce the cost of configuring custom processes and merge some non-essential nodes. Of course, the introduction of the ChatGPT configuration item here has a cost for most users (including myself).

Therefore, I hope that this node configuration can be quickly and cheaply launched while supporting rich extensions. Based on these considerations, I suggest providing a clear option to configure the ChatGPT version, and using an extended JSON configuration item for other configurations. If there is no configuration, defaults will be read from the msg context. What do you think?

**Comment by rdshoep** [comment]
> I've updated the node to version 1.2.4 to include a similar approximation to what this feature request is about. Does this resolve the request or do you have any additional feedback or improvements?

You are really efficient! Version `1.2.4` has already met my current usage needs~

**Pull request closed without merging**
