### PR TITLE
feat: support custom baseUrl

### PR DESCRIPTION
**Pull request by rdshoep**
Many countries in Asia cannot access OpenAI normally, so we need to configure the proxy domain name address.

### CODE REVIEW

**Comment by HaroldPetersInskipp** [comment]
That sounds like a useful addition for those that need it. However, to keep things easy for beginners using this node we will want to have that feature documented in the `<h2>Setup</h2>` section of `chatgpt.html` as a paragraph element. Nothing overly complex, just a concise description of how to set it up, like a quick-start section would have.

**Comment by rdshoep** [comment]
Got it. Can you easily understand the usage based on the new instructions added?

**Review by HaroldPetersInskipp — APPROVED** [review]
I made some slight alterations to the setup instructions, but other than that it looks good to go. Thank you again for your contribution.

**Comment by rdshoep** [comment]
You're welcome. I have already upgraded to the latest version v1.2.9 in my project.~

**Pull request merged**
